SELECT b.AUTHOR_ID, c.AUTHOR_NAME, b.CATEGORY, SUM(a.SALES * b.PRICE) TOTAL_SALES
FROM BOOK_SALES a LEFT JOIN Book b ON a.BOOK_ID = b.BOOK_ID
LEFT JOIN AUTHOR c ON b.AUTHOR_ID = c.AUTHOR_ID
WHERE a.SALES_DATE >= '2022-01-01' AND a.SALES_DATE < '2022-02-01'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC