WITH RECURSIVE CTE(ID, PARENT_ID, GENERATION) AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT a.ID, a.PARENT_ID, GENERATION + 1 
    FROM ECOLI_DATA a
    INNER JOIN CTE b ON a.PARENT_ID = b.ID
)

SELECT COUNT(*) COUNT, GENERATION
FROM CTE c
WHERE c.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION