SELECT b.USER_ID, b.NICKNAME, a.TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) a LEFT JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
ORDER BY TOTAL_SALES