SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
SELECT a.ITEM_ID
FROM ITEM_TREE a INNER JOIN ITEM_INFO b ON a.PARENT_ITEM_ID = b.ITEM_ID
WHERE b.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC