SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a LEFT JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE (a.FISH_TYPE, a.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY a.ID