SELECT b.CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES a LEFT JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY